title: Informe
author: Javier Mendoza López
email: alu0101320779@ull.edu.es
description: >
  En este informe se van viendo como realizo los ejercicios planteados por el profesor.
github_username:  alu0101320779 

show_excerpts: false
theme: minima
